<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CarvingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('carvings')->delete();
        
        \DB::table('carvings')->insert(array (
            0 => 
            array (
                'id' => 49,
                'category' => 'trays',
                'name' => 'Snowman Catch All',
                'description' => 'Snowman Catch All Tray',
                'views' => 5,
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'price' => 25,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'jobSheet' => NULL,
                'completed_at' => NULL,
                'created_at' => '2020-12-24 11:44:48',
                'updated_at' => '2021-01-23 15:55:59',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 50,
                'category' => 'trays',
                'name' => 'Puppy Catch All',
                'description' => 'Puppy Catch All Tray',
                'views' => 8,
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'price' => 30,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'jobSheet' => NULL,
                'completed_at' => NULL,
                'created_at' => '2020-12-24 11:45:12',
                'updated_at' => '2021-01-23 15:55:59',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 51,
                'category' => 'other',
                'name' => 'Heart shaped box',
                'description' => 'Heart shaped box',
                'views' => 13,
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'price' => 20,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'jobSheet' => NULL,
                'completed_at' => NULL,
                'created_at' => '2020-11-01 20:16:15',
                'updated_at' => '2021-01-23 15:47:01',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 52,
                'category' => 'signs',
                'name' => 'Welcome Santa',
                'description' => 'Welcome Santa',
                'views' => 2,
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'price' => 15,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'jobSheet' => NULL,
                'completed_at' => NULL,
                'created_at' => '2020-12-26 16:18:55',
                'updated_at' => '2021-01-23 15:55:59',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 53,
                'category' => 'dishes',
                'name' => 'Pumpkin Tray ABC',
                'description' => 'Pumpkin Tray',
                'views' => 28,
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'price' => 26,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'jobSheet' => NULL,
                'completed_at' => NULL,
                'created_at' => '2020-12-27 00:21:14',
                'updated_at' => '2021-06-14 07:42:42',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 54,
                'category' => 'other',
                'name' => 'X-Mas Ornament',
                'description' => 'X-Mas Santa Ornament',
                'views' => 1,
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'price' => 15,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'jobSheet' => NULL,
                'completed_at' => NULL,
                'created_at' => '2020-12-27 17:36:12',
                'updated_at' => '2021-06-02 21:12:04',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 55,
                'category' => 'dishes',
                'name' => '123456',
                'description' => 'asasas',
                'views' => 235,
                'design_time_hrs' => 5,
                'design_time_mins' => 6,
                'machine_time_hrs' => 7,
                'machine_time_mins' => 8,
                'price' => 50,
                'width' => '1',
                'depth' => '3',
                'height' => '2',
                'weight' => '4',
                'jobSheet' => '1617456803.html',
                'completed_at' => '2021-06-09 12:07:00',
                'created_at' => '2020-12-30 14:56:56',
                'updated_at' => '2021-06-09 12:07:13',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 56,
                'category' => 'coasters',
                'name' => 'categories 123',
                'description' => 'sdsdsds qwerty',
                'views' => 3,
                'design_time_hrs' => 2,
                'design_time_mins' => 15,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'price' => 100,
                'width' => '31.5',
                'depth' => NULL,
                'height' => '5.25',
                'weight' => NULL,
                'jobSheet' => NULL,
                'completed_at' => NULL,
                'created_at' => '2020-12-30 15:03:16',
                'updated_at' => '2021-04-03 07:01:57',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 57,
                'category' => 'plaques',
                'name' => '123456789012345678901234567890',
                'description' => 'sadsadsa',
                'views' => 0,
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'price' => 6,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'jobSheet' => NULL,
                'completed_at' => NULL,
                'created_at' => '2020-12-30 15:05:36',
                'updated_at' => '2020-12-30 15:09:16',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 58,
                'category' => 'trays',
                'name' => 'aaaaaaaaaa',
                'description' => 'aaaaa',
                'views' => 1,
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'price' => 18,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'jobSheet' => NULL,
                'completed_at' => NULL,
                'created_at' => '2020-12-30 15:07:31',
                'updated_at' => '2020-12-30 15:09:16',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 59,
                'category' => 'other',
                'name' => 'zxczxczxcxz',
                'description' => 'ssdasdsa sad sa dsa dsa',
                'views' => 0,
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'price' => 18,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'jobSheet' => NULL,
                'completed_at' => NULL,
                'created_at' => '2020-12-30 15:08:54',
                'updated_at' => '2020-12-30 15:09:22',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 60,
                'category' => 'other',
                'name' => 'Apple shaped keep sake box',
                'description' => 'Apple shaped keep sake box test',
                'views' => 10,
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'price' => 18,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'jobSheet' => NULL,
                'completed_at' => NULL,
                'created_at' => '2021-01-17 12:43:24',
                'updated_at' => '2021-01-19 21:51:37',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 61,
                'category' => 'trays',
                'name' => 'dsdsd',
                'description' => 'dsdsds',
                'views' => 0,
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'price' => 18,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'jobSheet' => NULL,
                'completed_at' => NULL,
                'created_at' => '2021-06-14 11:31:33',
                'updated_at' => '2021-06-14 11:31:33',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}