<?php

// namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CarvingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('carvings')->delete();
        
        \DB::table('carvings')->insert(array (
            0 => 
            array (
                'category' => 'trays',
                'completed_at' => NULL,
                'created_at' => '2020-12-24 11:44:48',
                'deleted_at' => NULL,
                'depth' => NULL,
                'description' => 'Snowman Catch All Tray',
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'height' => NULL,
                'id' => 49,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'name' => 'Snowman Catch All',
                'price' => NULL,
                'updated_at' => '2021-01-23 15:55:59',
                'views' => 0,
                'weight' => NULL,
                'width' => NULL,
            ),
            1 => 
            array (
                'category' => 'trays',
                'completed_at' => NULL,
                'created_at' => '2020-12-24 11:45:12',
                'deleted_at' => NULL,
                'depth' => NULL,
                'description' => 'Puppy Catch All Tray',
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'height' => NULL,
                'id' => 50,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'name' => 'Puppy Catch All',
                'price' => NULL,
                'updated_at' => '2021-01-23 15:55:59',
                'views' => 0,
                'weight' => NULL,
                'width' => NULL,
            ),
            2 => 
            array (
                'category' => 'other',
                'completed_at' => NULL,
                'created_at' => '2020-11-01 20:16:15',
                'deleted_at' => '2021-01-23 15:47:01',
                'depth' => NULL,
                'description' => 'Heart shaped box',
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'height' => NULL,
                'id' => 51,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'name' => 'Heart shaped box',
                'price' => NULL,
                'updated_at' => '2021-01-23 15:47:01',
                'views' => 13,
                'weight' => NULL,
                'width' => NULL,
            ),
            3 => 
            array (
                'category' => 'signs',
                'completed_at' => NULL,
                'created_at' => '2020-12-26 16:18:55',
                'deleted_at' => NULL,
                'depth' => NULL,
                'description' => 'Welcome Santa',
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'height' => NULL,
                'id' => 52,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'name' => 'Welcome Santa',
                'price' => NULL,
                'updated_at' => '2021-01-23 15:55:59',
                'views' => 0,
                'weight' => NULL,
                'width' => NULL,
            ),
            4 => 
            array (
                'category' => 'dishes',
                'completed_at' => NULL,
                'created_at' => '2020-12-27 00:21:14',
                'deleted_at' => NULL,
                'depth' => NULL,
                'description' => 'Pumpkin Tray',
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'height' => NULL,
                'id' => 53,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'name' => 'Pumpkin Tray',
                'price' => NULL,
                'updated_at' => '2021-01-26 21:37:29',
                'views' => 2,
                'weight' => NULL,
                'width' => NULL,
            ),
            5 => 
            array (
                'category' => 'other',
                'completed_at' => NULL,
                'created_at' => '2020-12-27 17:36:12',
                'deleted_at' => NULL,
                'depth' => NULL,
                'description' => 'X-Mas Santa Ornament',
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'height' => NULL,
                'id' => 54,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'name' => 'X-Mas Ornament',
                'price' => NULL,
                'updated_at' => '2021-01-23 15:55:59',
                'views' => 0,
                'weight' => NULL,
                'width' => NULL,
            ),
            6 => 
            array (
                'category' => 'coasters',
                'completed_at' => NULL,
                'created_at' => '2020-12-30 14:56:56',
                'deleted_at' => NULL,
                'depth' => NULL,
                'description' => 'asasas',
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'height' => NULL,
                'id' => 55,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'name' => '123456',
                'price' => NULL,
                'updated_at' => '2020-12-30 15:09:16',
                'views' => 58,
                'weight' => NULL,
                'width' => NULL,
            ),
            7 => 
            array (
                'category' => 'coasters',
                'completed_at' => NULL,
                'created_at' => '2020-12-30 15:03:16',
                'deleted_at' => NULL,
                'depth' => NULL,
                'description' => 'sdsdsds',
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'height' => NULL,
                'id' => 56,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'name' => 'categories',
                'price' => NULL,
                'updated_at' => '2020-12-30 15:09:16',
                'views' => 0,
                'weight' => NULL,
                'width' => NULL,
            ),
            8 => 
            array (
                'category' => 'plaques',
                'completed_at' => NULL,
                'created_at' => '2020-12-30 15:05:36',
                'deleted_at' => '2020-12-30 15:09:16',
                'depth' => NULL,
                'description' => 'sadsadsa',
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'height' => NULL,
                'id' => 57,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'name' => '123456789012345678901234567890',
                'price' => NULL,
                'updated_at' => '2020-12-30 15:09:16',
                'views' => 0,
                'weight' => NULL,
                'width' => NULL,
            ),
            9 => 
            array (
                'category' => 'trays',
                'completed_at' => NULL,
                'created_at' => '2020-12-30 15:07:31',
                'deleted_at' => '2020-12-30 15:09:16',
                'depth' => NULL,
                'description' => 'aaaaa',
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'height' => NULL,
                'id' => 58,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'name' => 'aaaaaaaaaa',
                'price' => NULL,
                'updated_at' => '2020-12-30 15:09:16',
                'views' => 0,
                'weight' => NULL,
                'width' => NULL,
            ),
            10 => 
            array (
                'category' => 'other',
                'completed_at' => NULL,
                'created_at' => '2020-12-30 15:08:54',
                'deleted_at' => '2020-12-30 15:09:22',
                'depth' => NULL,
                'description' => 'ssdasdsa sad sa dsa dsa',
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'height' => NULL,
                'id' => 59,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'name' => 'zxczxczxcxz',
                'price' => NULL,
                'updated_at' => '2020-12-30 15:09:22',
                'views' => 0,
                'weight' => NULL,
                'width' => NULL,
            ),
            11 => 
            array (
                'category' => 'other',
                'completed_at' => NULL,
                'created_at' => '2021-01-17 12:43:24',
                'deleted_at' => '2021-01-19 21:51:37',
                'depth' => NULL,
                'description' => 'Apple shaped keep sake box test',
                'design_time_hrs' => NULL,
                'design_time_mins' => NULL,
                'height' => NULL,
                'id' => 60,
                'machine_time_hrs' => NULL,
                'machine_time_mins' => NULL,
                'name' => 'Apple shaped keep sake box',
                'price' => NULL,
                'updated_at' => '2021-01-19 21:51:37',
                'views' => 10,
                'weight' => NULL,
                'width' => NULL,
            ),
        ));
        
        
    }
}