<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CopyInvoicerInvoicesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('copy_invoicer__invoices')->delete();
        
        \DB::table('copy_invoicer__invoices')->insert(array (
            0 => 
            array (
                'id' => 66,
                'client_id' => 18,
                'notes' => NULL,
                'status' => 'estimate',
                'amount_charged' => '20.00',
                'hst' => '1.40',
                'sub_total' => '21.40',
                'wsib' => '0.00',
                'income_taxes' => '0.00',
                'total_deductions' => '0.00',
                'deposits' => '0.00',
                'discounts' => '0.00',
                'payments' => '0.00',
                'total' => '21.40',
                'logged_at' => NULL,
                'invoiced_at' => NULL,
                'paid_at' => NULL,
                'created_at' => '2021-05-17 06:28:06',
                'updated_at' => '2021-05-19 14:25:33',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 67,
                'client_id' => 7,
                'notes' => NULL,
                'status' => 'paid',
                'amount_charged' => '50.00',
                'hst' => '3.50',
                'sub_total' => '53.50',
                'wsib' => '0.00',
                'income_taxes' => '0.00',
                'total_deductions' => '0.00',
                'deposits' => '0.00',
                'discounts' => '0.00',
                'payments' => '53.50',
                'total' => '0.00',
                'logged_at' => '2021-05-19 20:24:39',
                'invoiced_at' => '2021-05-31 08:56:01',
                'paid_at' => '2021-05-31 08:56:01',
                'created_at' => '2021-05-19 20:24:39',
                'updated_at' => '2021-05-31 08:56:01',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 68,
                'client_id' => 18,
                'notes' => NULL,
                'status' => 'logged',
                'amount_charged' => NULL,
                'hst' => NULL,
                'sub_total' => NULL,
                'wsib' => NULL,
                'income_taxes' => NULL,
                'total_deductions' => NULL,
                'deposits' => NULL,
                'discounts' => NULL,
                'payments' => NULL,
                'total' => NULL,
                'logged_at' => '2021-06-01 22:11:08',
                'invoiced_at' => NULL,
                'paid_at' => NULL,
                'created_at' => '2021-06-01 22:11:08',
                'updated_at' => '2021-06-01 22:11:08',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 69,
                'client_id' => 7,
                'notes' => NULL,
                'status' => 'logged',
                'amount_charged' => NULL,
                'hst' => NULL,
                'sub_total' => NULL,
                'wsib' => NULL,
                'income_taxes' => NULL,
                'total_deductions' => NULL,
                'deposits' => NULL,
                'discounts' => NULL,
                'payments' => NULL,
                'total' => NULL,
                'logged_at' => '2021-06-05 20:45:24',
                'invoiced_at' => NULL,
                'paid_at' => NULL,
                'created_at' => '2021-06-05 20:45:24',
                'updated_at' => '2021-06-05 20:45:24',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 70,
                'client_id' => 7,
                'notes' => NULL,
                'status' => 'logged',
                'amount_charged' => '35.00',
                'hst' => '2.45',
                'sub_total' => '37.45',
                'wsib' => '0.00',
                'income_taxes' => '0.00',
                'total_deductions' => '0.00',
                'deposits' => '0.00',
                'discounts' => '1.75',
                'payments' => '0.00',
                'total' => '35.70',
                'logged_at' => '2021-06-05 20:50:02',
                'invoiced_at' => NULL,
                'paid_at' => NULL,
                'created_at' => '2021-06-05 20:50:02',
                'updated_at' => '2021-06-05 20:58:49',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 71,
                'client_id' => 7,
                'notes' => NULL,
                'status' => 'estimate',
                'amount_charged' => '100.00',
                'hst' => '7.00',
                'sub_total' => '107.00',
                'wsib' => '0.00',
                'income_taxes' => '0.00',
                'total_deductions' => '0.00',
                'deposits' => '0.00',
                'discounts' => '7.00',
                'payments' => '0.00',
                'total' => '100.00',
                'logged_at' => NULL,
                'invoiced_at' => NULL,
                'paid_at' => NULL,
                'created_at' => '2021-06-05 21:03:53',
                'updated_at' => '2021-06-06 07:26:12',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 72,
                'client_id' => 1,
                'notes' => NULL,
                'status' => 'logged',
                'amount_charged' => NULL,
                'hst' => NULL,
                'sub_total' => NULL,
                'wsib' => NULL,
                'income_taxes' => NULL,
                'total_deductions' => NULL,
                'deposits' => NULL,
                'discounts' => NULL,
                'payments' => NULL,
                'total' => NULL,
                'logged_at' => '2021-06-05 21:04:20',
                'invoiced_at' => NULL,
                'paid_at' => NULL,
                'created_at' => '2021-06-05 21:04:20',
                'updated_at' => '2021-06-05 21:04:20',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 73,
                'client_id' => 2,
                'notes' => NULL,
                'status' => 'logged',
                'amount_charged' => '250.00',
                'hst' => '17.50',
                'sub_total' => '267.50',
                'wsib' => '0.00',
                'income_taxes' => '0.00',
                'total_deductions' => '0.00',
                'deposits' => '0.00',
                'discounts' => '0.00',
                'payments' => '0.00',
                'total' => '267.50',
                'logged_at' => '2021-06-05 21:10:13',
                'invoiced_at' => NULL,
                'paid_at' => NULL,
                'created_at' => '2021-06-05 21:10:13',
                'updated_at' => '2021-06-05 21:14:24',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 74,
                'client_id' => 7,
                'notes' => NULL,
                'status' => 'logged',
                'amount_charged' => '35.00',
                'hst' => '2.45',
                'sub_total' => '37.45',
                'wsib' => '0.00',
                'income_taxes' => '0.00',
                'total_deductions' => '0.00',
                'deposits' => '0.00',
                'discounts' => '0.00',
                'payments' => '0.00',
                'total' => '37.45',
                'logged_at' => '2021-06-05 21:36:22',
                'invoiced_at' => NULL,
                'paid_at' => NULL,
                'created_at' => '2021-06-05 21:36:22',
                'updated_at' => '2021-06-18 05:35:06',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}