<?php

use Illuminate\Database\Seeder;

class ProjectsProjectsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('projects__projects')->delete();
        
        \DB::table('projects__projects')->insert(array (
            0 => 
            array (
                'id' => 11,
                'category' => 2,
                'name' => 'Hallway table',
                'description' => 'Nice hallway table with ceramic tile top',
                'views' => 109,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'completed_at' => NULL,
                'created_at' => '2019-07-22 02:12:18',
                'updated_at' => '2019-07-22 02:12:18',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 12,
                'category' => 2,
                'name' => 'Storage Bench',
                'description' => 'Storage Bench',
                'views' => 99,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'completed_at' => NULL,
                'created_at' => '2019-07-22 20:42:54',
                'updated_at' => '2019-07-22 20:42:54',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 13,
                'category' => 5,
                'name' => 'Chalkboard',
                'description' => 'Small chalkboard',
                'views' => 40,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'completed_at' => NULL,
                'created_at' => '2019-07-22 20:43:42',
                'updated_at' => '2019-07-22 20:43:42',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 14,
                'category' => 1,
                'name' => 'Candle Box',
                'description' => 'Candle box',
                'views' => 117,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'completed_at' => NULL,
                'created_at' => '2019-07-22 20:44:44',
                'updated_at' => '2019-07-29 00:40:07',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 15,
                'category' => 1,
                'name' => 'Candle Holder',
                'description' => 'Candle Holder',
                'views' => 101,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'completed_at' => NULL,
                'created_at' => '2019-07-22 20:44:59',
                'updated_at' => '2019-07-29 00:40:30',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 18,
                'category' => 5,
                'name' => 'Corner Shelf',
                'description' => 'Corner Shelf',
                'views' => 61,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'completed_at' => NULL,
                'created_at' => '2019-07-26 10:28:32',
                'updated_at' => '2019-07-26 10:30:53',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 19,
                'category' => 5,
                'name' => 'Antique mirror',
                'description' => 'Antique mirror',
                'views' => 157,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'completed_at' => NULL,
                'created_at' => '2019-07-26 10:28:56',
                'updated_at' => '2019-07-26 10:28:56',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 20,
                'category' => 5,
                'name' => 'Wine Rack',
                'description' => 'Wine Rack',
                'views' => 57,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'completed_at' => NULL,
                'created_at' => '2019-07-26 10:29:12',
                'updated_at' => '2019-07-26 10:29:12',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 22,
                'category' => 4,
                'name' => 'Slatted Shelving Unit',
                'description' => 'A multi level shelving unit built with evenly spaced slats',
                'views' => 9,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'completed_at' => NULL,
                'created_at' => '2019-12-23 23:54:21',
                'updated_at' => '2019-12-23 23:54:21',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 23,
                'category' => 2,
                'name' => 'Dining room table bench',
                'description' => 'Dining room table bench',
                'views' => 11,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'completed_at' => NULL,
                'created_at' => '2019-12-23 23:54:49',
                'updated_at' => '2019-12-23 23:54:49',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 24,
                'category' => 2,
                'name' => 'Night stand',
                'description' => 'A night stand',
                'views' => 11,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'completed_at' => NULL,
                'created_at' => '2020-04-22 17:52:13',
                'updated_at' => '2020-04-22 17:52:13',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 25,
                'category' => 5,
                'name' => 'Wall mounted coat rack',
                'description' => 'Wall mounted coat rack made for our home.',
                'views' => 10,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => 60,
                'depth' => NULL,
                'height' => 36,
                'weight' => NULL,
                'completed_at' => '2020-04-18 15:03:00',
                'created_at' => '2020-04-22 18:00:50',
                'updated_at' => '2020-07-20 19:03:57',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 26,
                'category' => 2,
                'name' => 'Light box',
                'description' => 'Light box',
                'views' => 6,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => NULL,
                'depth' => NULL,
                'height' => NULL,
                'weight' => NULL,
                'completed_at' => NULL,
                'created_at' => '2020-04-22 18:04:48',
                'updated_at' => '2020-04-22 18:04:48',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 27,
                'category' => 5,
                'name' => 'small wall mounted coat rack',
                'description' => 'This was a smaller coat rack made for best friends. 
Built as 30" x 36" and will hang on the wall securely with a french cleat.',
                'views' => 6,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => 36,
                'depth' => NULL,
                'height' => 30,
                'weight' => NULL,
                'completed_at' => '2020-06-22 14:55:00',
                'created_at' => '2020-07-20 18:53:07',
                'updated_at' => '2020-07-20 18:56:38',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 28,
                'category' => 2,
                'name' => 'unique outdoor side tables',
                'description' => 'This set was made for best friends to use by their campfire at a campground.
They will be treated with a water shield but not stained.',
                'views' => 6,
                'time_invested' => NULL,
                'price' => NULL,
                'width' => 14,
                'depth' => 22,
                'height' => 17,
                'weight' => NULL,
                'completed_at' => '2020-07-18 14:55:00',
                'created_at' => '2020-07-20 19:16:03',
                'updated_at' => '2020-07-20 19:22:25',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}