<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'username' => 'admin',
                'first_name' => 'Admin',
                'last_name' => 'User',
                'account_status' => 1,
                'email' => 'admin@admin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6mO/sENF07xOxKprzD7Cq.eo7GiuvtrxEa/3n8bJI5LkM3IqUsBgy',
                'remember_token' => NULL,
                'created_at' => '2020-09-07 08:51:04',
                'updated_at' => '2020-09-08 07:11:30',
                'deleted_at' => NULL,
                'public_email' => 1,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'The Admin Company',
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => 1,
                'previous_login_date' => '2020-09-07 23:38:53',
                'last_login_date' => '2020-09-08 07:11:30',
                'login_count' => 5,
            ),
            1 => 
            array (
                'id' => 2,
                'username' => 'lerouxs',
                'first_name' => 'Stephane',
                'last_name' => 'Leroux',
                'account_status' => 1,
                'email' => 'stleroux@hotmail.ca',
                'email_verified_at' => '2020-09-08 03:34:09',
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'remember_token' => NULL,
                'created_at' => '2020-09-08 03:34:09',
                'updated_at' => '2020-09-08 07:12:01',
                'deleted_at' => NULL,
                'public_email' => 1,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'TheWoodBarn.ca',
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => 1,
                'previous_login_date' => '2020-09-07 23:39:05',
                'last_login_date' => '2020-09-08 07:12:01',
                'login_count' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'username' => 'hayness',
                'first_name' => 'Stacie',
                'last_name' => 'Haynes',
                'account_status' => 1,
                'email' => 'stacie.haynes@hotmail.com',
                'email_verified_at' => NULL,
                'password' => '5f4dcc3b5aa765d61d8327deb882cf99',
                'remember_token' => NULL,
                'created_at' => '2020-09-08 11:22:45',
                'updated_at' => '2020-09-08 11:22:45',
                'deleted_at' => NULL,
                'public_email' => 0,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'Stacie Haynes Inc',
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => 1,
                'previous_login_date' => NULL,
                'last_login_date' => NULL,
                'login_count' => 0,
            ),
            3 => 
            array (
                'id' => 5,
                'username' => 'leveillel',
                'first_name' => 'Luc',
                'last_name' => 'Leveille',
                'account_status' => 1,
                'email' => 'leveillel@gmail.com',
                'email_verified_at' => '2020-09-08 11:23:54',
                'password' => '5f4dcc3b5aa765d61d8327deb882cf99',
                'remember_token' => NULL,
                'created_at' => '2020-09-08 11:23:54',
                'updated_at' => '2020-09-08 11:23:54',
                'deleted_at' => NULL,
                'public_email' => 1,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'Leveille Trim',
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => 1,
                'previous_login_date' => NULL,
                'last_login_date' => NULL,
                'login_count' => 0,
            ),
            4 => 
            array (
                'id' => 7,
                'username' => 'haynesb',
                'first_name' => 'Brenda',
                'last_name' => 'Haynes',
                'account_status' => 1,
                'email' => 'brenda.haynes@example.com',
                'email_verified_at' => '2020-09-08 11:24:40',
                'password' => '5f4dcc3b5aa765d61d8327deb882cf99',
                'remember_token' => NULL,
                'created_at' => '2020-09-08 11:24:40',
                'updated_at' => '2020-09-08 11:24:40',
                'deleted_at' => NULL,
                'public_email' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => NULL,
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => NULL,
                'previous_login_date' => NULL,
                'last_login_date' => NULL,
                'login_count' => 0,
            ),
            5 => 
            array (
                'id' => 20,
                'username' => 'author',
                'first_name' => 'Author',
                'last_name' => 'User',
                'account_status' => 0,
                'email' => 'author@author.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$4wRLKlJmly1k/hezj8ljOufFhv4wicjYlAYSCHo..tldO3tOUV85K',
                'remember_token' => NULL,
                'created_at' => '2020-09-07 08:51:05',
                'updated_at' => '2020-09-07 08:51:05',
                'deleted_at' => NULL,
                'public_email' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => NULL,
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => NULL,
                'previous_login_date' => NULL,
                'last_login_date' => NULL,
                'login_count' => 0,
            ),
            6 => 
            array (
                'id' => 23,
                'username' => 'generic',
                'first_name' => 'Generic',
                'last_name' => 'User',
                'account_status' => 0,
                'email' => 'user@user.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$PvktleuFxX154aoaYcv9dOkqlj4kB0euFVZf.XKQM1yCdrTlRP8QC',
                'remember_token' => NULL,
                'created_at' => '2020-09-07 08:51:05',
                'updated_at' => '2020-09-07 08:51:05',
                'deleted_at' => NULL,
                'public_email' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => NULL,
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => NULL,
                'previous_login_date' => NULL,
                'last_login_date' => NULL,
                'login_count' => 0,
            ),
            7 => 
            array (
                'id' => 25,
                'username' => 'khaynes',
                'first_name' => 'Kyle',
                'last_name' => 'Duperron-Haynes',
                'account_status' => 1,
                'email' => 'kdupe071@uottawa.ca',
                'email_verified_at' => NULL,
                'password' => '$2y$10$VSfDNbTDEY16FF2uKdd/NenWf7YJ3LfNGAMYXT7eF5omc0Z0lTQQK',
                'remember_token' => NULL,
                'created_at' => '2020-03-25 18:11:55',
                'updated_at' => '2020-09-03 00:46:42',
                'deleted_at' => NULL,
                'public_email' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => NULL,
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 16,
                'invoicer_client' => NULL,
                'previous_login_date' => '2020-07-28 20:43:32',
                'last_login_date' => '2020-09-03 00:46:42',
                'login_count' => 9,
            ),
            8 => 
            array (
                'id' => 27,
                'username' => 'Tdot',
                'first_name' => 'Victoria',
                'last_name' => 'Duperron-Haynes',
                'account_status' => 1,
                'email' => 'vdg0909@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$JpgXRbmon6YQE8jZKEUVEecsEQAiFSvJBtG1DCL3h5cc9vIyYPscO',
                'remember_token' => NULL,
                'created_at' => '2020-03-30 17:35:38',
                'updated_at' => '2020-03-30 17:37:52',
                'deleted_at' => NULL,
                'public_email' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => NULL,
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => NULL,
                'previous_login_date' => NULL,
                'last_login_date' => '2020-03-30 17:36:34',
                'login_count' => 1,
            ),
        ));
        
        
    }
}