<?php

// namespace Database\Seeds;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'account_status' => 1,
                'address_1' => '1216 Ste Marie Rd',
                'address_2' => NULL,
                'cell' => NULL,
                'city' => 'Embrun',
                'company_name' => 'TheWoodBarn.ca',
                'created_at' => '2020-09-07 08:51:04',
                'dart_doubleOut' => 0,
                'deleted_at' => NULL,
                'email' => 'stephaneandstacie@gmail.com',
                'email_verified_at' => NULL,
                'fax' => NULL,
                'first_name' => 'Stephane',
                'id' => 1,
                'image' => NULL,
                'invoicer_client' => 0,
                'last_login_date' => '2020-11-11 10:44:24',
                'last_name' => 'Leroux',
                'login_count' => 116,
                'notes' => NULL,
                'password' => '$2y$10$6mO/sENF07xOxKprzD7Cq.eo7GiuvtrxEa/3n8bJI5LkM3IqUsBgy',
                'postal_code' => 'K0A-1W0',
                'previous_login_date' => '2020-11-10 21:24:17',
                'province' => 'Ontario',
                'public_email' => 0,
                'reasonToRegister' => '',
                'remember_token' => NULL,
            'telephone' => '(613) 370-0275',
                'updated_at' => '2020-11-11 10:44:24',
                'username' => 'admin',
                'website' => 'TheWoodBarn.ca',
            ),
            1 => 
            array (
                'account_status' => 1,
                'address_1' => '1216 Ste Marie Rd',
                'address_2' => NULL,
                'cell' => NULL,
                'city' => 'Embrun',
                'company_name' => 'TheWoodBarn.ca',
                'created_at' => '2020-09-08 03:34:09',
                'dart_doubleOut' => 10,
                'deleted_at' => NULL,
                'email' => 'stleroux@hotmail.ca',
                'email_verified_at' => '2020-09-08 03:34:09',
                'fax' => NULL,
                'first_name' => 'Stephane',
                'id' => 2,
                'image' => NULL,
                'invoicer_client' => 1,
                'last_login_date' => '2021-01-29 07:44:01',
                'last_name' => 'Leroux',
                'login_count' => 105,
                'notes' => NULL,
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'postal_code' => 'K0A-1W0',
                'previous_login_date' => '2021-01-28 20:26:55',
                'province' => 'Ontario',
                'public_email' => 1,
                'reasonToRegister' => '',
                'remember_token' => NULL,
            'telephone' => '(613) 370-0275',
                'updated_at' => '2021-01-29 07:44:01',
                'username' => 'lerouxs',
                'website' => NULL,
            ),
            2 => 
            array (
                'account_status' => 1,
                'address_1' => '1216 Ste Marie Rd',
                'address_2' => NULL,
                'cell' => NULL,
                'city' => 'Embrun',
                'company_name' => 'Stacie Haynes Inc',
                'created_at' => '2020-09-08 11:22:45',
                'dart_doubleOut' => 10,
                'deleted_at' => NULL,
                'email' => 'staciehaynes@hotmail.com',
                'email_verified_at' => NULL,
                'fax' => NULL,
                'first_name' => 'Stacie',
                'id' => 3,
                'image' => NULL,
                'invoicer_client' => 1,
                'last_login_date' => '2021-01-21 21:58:04',
                'last_name' => 'Haynes',
                'login_count' => 16,
                'notes' => NULL,
                'password' => '$2y$10$LAOKEiQwZbhw8/4cykmmSeSeUAJb4NBXG8bNaQhmwY3TQvKCH92Tm',
                'postal_code' => 'K0A-1W0',
                'previous_login_date' => '2021-01-15 08:29:47',
                'province' => 'Ontario',
                'public_email' => 0,
                'reasonToRegister' => '',
                'remember_token' => NULL,
            'telephone' => '(613) 327-4722',
                'updated_at' => '2021-01-21 21:58:04',
                'username' => 'hayness',
                'website' => NULL,
            ),
            3 => 
            array (
                'account_status' => 1,
                'address_1' => NULL,
                'address_2' => NULL,
                'cell' => NULL,
                'city' => NULL,
                'company_name' => NULL,
                'created_at' => '2020-10-10 04:20:28',
                'dart_doubleOut' => 0,
                'deleted_at' => NULL,
                'email' => 'tremblayj@email.com',
                'email_verified_at' => NULL,
                'fax' => NULL,
                'first_name' => 'Julien',
                'id' => 4,
                'image' => NULL,
                'invoicer_client' => NULL,
                'last_login_date' => NULL,
                'last_name' => 'Tremblay',
                'login_count' => 0,
                'notes' => NULL,
                'password' => '',
                'postal_code' => NULL,
                'previous_login_date' => NULL,
                'province' => NULL,
                'public_email' => NULL,
                'reasonToRegister' => '',
                'remember_token' => NULL,
                'telephone' => NULL,
                'updated_at' => '2020-10-17 08:35:34',
                'username' => 'tremblayj',
                'website' => NULL,
            ),
            4 => 
            array (
                'account_status' => 1,
                'address_1' => NULL,
                'address_2' => NULL,
                'cell' => NULL,
                'city' => NULL,
                'company_name' => 'Leveille Trim',
                'created_at' => '2020-09-08 11:23:54',
                'dart_doubleOut' => 10,
                'deleted_at' => NULL,
                'email' => 'leveillel@gmail.com',
                'email_verified_at' => '2020-09-08 11:23:54',
                'fax' => NULL,
                'first_name' => 'Luc',
                'id' => 5,
                'image' => NULL,
                'invoicer_client' => 1,
                'last_login_date' => NULL,
                'last_name' => 'Leveille',
                'login_count' => 0,
                'notes' => NULL,
                'password' => '5f4dcc3b5aa765d61d8327deb882cf99',
                'postal_code' => NULL,
                'previous_login_date' => NULL,
                'province' => NULL,
                'public_email' => 1,
                'reasonToRegister' => '',
                'remember_token' => NULL,
                'telephone' => NULL,
                'updated_at' => '2020-09-08 11:23:54',
                'username' => 'leveillel',
                'website' => NULL,
            ),
            5 => 
            array (
                'account_status' => 1,
                'address_1' => NULL,
                'address_2' => NULL,
                'cell' => NULL,
                'city' => NULL,
                'company_name' => NULL,
                'created_at' => '2020-10-10 04:20:43',
                'dart_doubleOut' => 10,
                'deleted_at' => NULL,
                'email' => 'haynesj@email.com',
                'email_verified_at' => NULL,
                'fax' => NULL,
                'first_name' => 'Jeffrey',
                'id' => 6,
                'image' => NULL,
                'invoicer_client' => NULL,
                'last_login_date' => NULL,
                'last_name' => 'Haynes',
                'login_count' => 0,
                'notes' => NULL,
                'password' => '',
                'postal_code' => NULL,
                'previous_login_date' => NULL,
                'province' => NULL,
                'public_email' => NULL,
                'reasonToRegister' => '',
                'remember_token' => NULL,
                'telephone' => NULL,
                'updated_at' => '2020-10-17 08:35:35',
                'username' => 'haynesj',
                'website' => NULL,
            ),
            6 => 
            array (
                'account_status' => 1,
                'address_1' => NULL,
                'address_2' => NULL,
                'cell' => NULL,
                'city' => NULL,
                'company_name' => NULL,
                'created_at' => '2020-09-08 11:24:40',
                'dart_doubleOut' => 10,
                'deleted_at' => NULL,
                'email' => 'brendahaynes@example.com',
                'email_verified_at' => '2020-09-08 11:24:40',
                'fax' => NULL,
                'first_name' => 'Brenda',
                'id' => 7,
                'image' => NULL,
                'invoicer_client' => 0,
                'last_login_date' => '2020-10-27 09:12:00',
                'last_name' => 'Haynes',
                'login_count' => 10,
                'notes' => NULL,
                'password' => '$2y$10$2wFWYndWpsbc8VsYQNR9ou6Hlw.Ctk8shv8/WtYfqwk1xcVspjfqu',
                'postal_code' => NULL,
                'previous_login_date' => '2020-10-26 12:00:11',
                'province' => NULL,
                'public_email' => 0,
                'reasonToRegister' => '',
                'remember_token' => NULL,
                'telephone' => NULL,
                'updated_at' => '2020-10-27 09:12:00',
                'username' => 'haynesb',
                'website' => NULL,
            ),
            7 => 
            array (
                'account_status' => 0,
                'address_1' => NULL,
                'address_2' => NULL,
                'cell' => NULL,
                'city' => NULL,
                'company_name' => NULL,
                'created_at' => '2020-06-05 11:54:16',
                'dart_doubleOut' => 0,
                'deleted_at' => NULL,
                'email' => 'author@author.com',
                'email_verified_at' => NULL,
                'fax' => NULL,
                'first_name' => 'Author',
                'id' => 20,
                'image' => NULL,
                'invoicer_client' => NULL,
                'last_login_date' => '2020-10-10 00:12:49',
                'last_name' => 'User',
                'login_count' => 7,
                'notes' => NULL,
                'password' => '$2y$10$4wRLKlJmly1k/hezj8ljOufFhv4wicjYlAYSCHo..tldO3tOUV85K',
                'postal_code' => NULL,
                'previous_login_date' => '2020-10-04 19:07:41',
                'province' => NULL,
                'public_email' => NULL,
                'reasonToRegister' => '',
                'remember_token' => NULL,
                'telephone' => NULL,
                'updated_at' => '2020-10-17 08:41:00',
                'username' => 'author',
                'website' => NULL,
            ),
            8 => 
            array (
                'account_status' => 0,
                'address_1' => NULL,
                'address_2' => NULL,
                'cell' => NULL,
                'city' => NULL,
                'company_name' => NULL,
                'created_at' => '2020-06-05 11:54:16',
                'dart_doubleOut' => 0,
                'deleted_at' => '2020-10-19 07:03:26',
                'email' => 'user@user.com',
                'email_verified_at' => NULL,
                'fax' => NULL,
                'first_name' => 'Generic',
                'id' => 23,
                'image' => NULL,
                'invoicer_client' => NULL,
                'last_login_date' => NULL,
                'last_name' => 'User',
                'login_count' => 0,
                'notes' => NULL,
                'password' => '$2y$10$PvktleuFxX154aoaYcv9dOkqlj4kB0euFVZf.XKQM1yCdrTlRP8QC',
                'postal_code' => NULL,
                'previous_login_date' => NULL,
                'province' => NULL,
                'public_email' => NULL,
                'reasonToRegister' => '',
                'remember_token' => NULL,
                'telephone' => NULL,
                'updated_at' => '2020-10-19 07:03:26',
                'username' => 'generic',
                'website' => NULL,
            ),
            9 => 
            array (
                'account_status' => 1,
                'address_1' => NULL,
                'address_2' => NULL,
                'cell' => NULL,
                'city' => NULL,
                'company_name' => NULL,
                'created_at' => '2020-03-25 18:11:55',
                'dart_doubleOut' => 16,
                'deleted_at' => NULL,
                'email' => 'kdupe071@uottawa.ca',
                'email_verified_at' => NULL,
                'fax' => NULL,
                'first_name' => 'Kyle',
                'id' => 25,
                'image' => NULL,
                'invoicer_client' => NULL,
                'last_login_date' => '2020-09-03 00:46:42',
                'last_name' => 'Duperron-Haynes',
                'login_count' => 9,
                'notes' => NULL,
                'password' => '$2y$10$VSfDNbTDEY16FF2uKdd/NenWf7YJ3LfNGAMYXT7eF5omc0Z0lTQQK',
                'postal_code' => NULL,
                'previous_login_date' => '2020-07-28 20:43:32',
                'province' => NULL,
                'public_email' => NULL,
                'reasonToRegister' => '',
                'remember_token' => NULL,
                'telephone' => NULL,
                'updated_at' => '2020-09-03 00:46:42',
                'username' => 'khaynes',
                'website' => NULL,
            ),
            10 => 
            array (
                'account_status' => 1,
                'address_1' => NULL,
                'address_2' => NULL,
                'cell' => NULL,
                'city' => NULL,
                'company_name' => NULL,
                'created_at' => '2020-03-30 17:35:38',
                'dart_doubleOut' => 10,
                'deleted_at' => NULL,
                'email' => 'vdg0909@gmail.com',
                'email_verified_at' => NULL,
                'fax' => NULL,
                'first_name' => 'Victoria',
                'id' => 27,
                'image' => NULL,
                'invoicer_client' => NULL,
                'last_login_date' => '2020-03-30 17:36:34',
                'last_name' => 'Duperron-Haynes',
                'login_count' => 1,
                'notes' => NULL,
                'password' => '$2y$10$JpgXRbmon6YQE8jZKEUVEecsEQAiFSvJBtG1DCL3h5cc9vIyYPscO',
                'postal_code' => NULL,
                'previous_login_date' => NULL,
                'province' => NULL,
                'public_email' => NULL,
                'reasonToRegister' => '',
                'remember_token' => NULL,
                'telephone' => NULL,
                'updated_at' => '2020-03-30 17:37:52',
                'username' => 'Tdot',
                'website' => NULL,
            ),
        ));
        
        
    }
}