<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'username' => 'admin',
                'first_name' => 'Stephane',
                'last_name' => 'Leroux',
                'account_status' => 1,
                'email' => 'stephaneandstacie@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6mO/sENF07xOxKprzD7Cq.eo7GiuvtrxEa/3n8bJI5LkM3IqUsBgy',
                'remember_token' => NULL,
                'created_at' => '2020-09-07 08:51:04',
                'updated_at' => '2021-02-18 08:32:33',
                'deleted_at' => NULL,
                'public_email' => 0,
            'telephone' => '(613) 370-0275',
                'cell' => NULL,
                'fax' => NULL,
                'website' => 'TheWoodBarn.ca',
                'company_name' => 'TheWoodBarn.ca',
                'image' => NULL,
                'address_1' => '1216 Ste Marie Rd',
                'address_2' => NULL,
                'city' => 'Embrun',
                'province' => 'Ontario',
                'postal_code' => 'K0A-1W0',
                'notes' => 'asasas as asasas',
                'dart_doubleOut' => 0,
                'invoicer_client' => 0,
                'previous_login_date' => '2020-11-11 10:44:24',
                'last_login_date' => '2021-02-18 08:32:33',
                'login_count' => 117,
                'reasonToRegister' => '',
                'redirectAfterLogin' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'username' => 'lerouxs',
                'first_name' => 'Stephane',
                'last_name' => 'Leroux',
                'account_status' => 1,
                'email' => 'stleroux@hotmail.ca',
                'email_verified_at' => '2020-09-08 03:34:09',
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'remember_token' => '3QH5VkhSZKIjVEnr4JqgfqoEOxbkEMtRqaCI7d98DVznZJ0GVvnyEeSJ8bAw',
                'created_at' => '2020-09-08 03:34:09',
                'updated_at' => '2021-07-01 06:46:01',
                'deleted_at' => NULL,
                'public_email' => 1,
            'telephone' => '(613) 370-0275',
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'TheWoodBarn.ca',
                'image' => NULL,
                'address_1' => '1216 Ste Marie Rd',
                'address_2' => NULL,
                'city' => 'Embrun',
                'province' => 'Ontario',
                'postal_code' => 'K0A-1W0',
                'notes' => 'Notes',
                'dart_doubleOut' => 10,
                'invoicer_client' => 1,
                'previous_login_date' => '2021-06-30 21:01:10',
                'last_login_date' => '2021-07-01 06:46:01',
                'login_count' => 348,
                'reasonToRegister' => '',
                'redirectAfterLogin' => '/admin/dashboard',
            ),
            2 => 
            array (
                'id' => 3,
                'username' => 'hayness',
                'first_name' => 'Stacie',
                'last_name' => 'Haynes',
                'account_status' => 1,
                'email' => 'staciehaynes@hotmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$LAOKEiQwZbhw8/4cykmmSeSeUAJb4NBXG8bNaQhmwY3TQvKCH92Tm',
                'remember_token' => NULL,
                'created_at' => '2020-09-08 11:22:45',
                'updated_at' => '2021-06-26 19:03:12',
                'deleted_at' => NULL,
                'public_email' => 0,
            'telephone' => '(613) 327-4722',
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'Stacie Haynes Inc',
                'image' => NULL,
                'address_1' => '1216 Ste Marie Rd',
                'address_2' => NULL,
                'city' => 'Embrun',
                'province' => 'Ontario',
                'postal_code' => 'K0A-1W0',
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => 0,
                'previous_login_date' => '2021-06-21 11:22:36',
                'last_login_date' => '2021-06-26 19:03:12',
                'login_count' => 31,
                'reasonToRegister' => '',
                'redirectAfterLogin' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'username' => 'tremblayj',
                'first_name' => 'Julien',
                'last_name' => 'Tremblay',
                'account_status' => 1,
                'email' => 'tremblayj@email.com',
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => NULL,
                'created_at' => '2020-10-10 04:20:28',
                'updated_at' => '2020-10-17 08:35:34',
                'deleted_at' => NULL,
                'public_email' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => NULL,
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 0,
                'invoicer_client' => 0,
                'previous_login_date' => NULL,
                'last_login_date' => NULL,
                'login_count' => 0,
                'reasonToRegister' => '',
                'redirectAfterLogin' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'username' => 'leveillel',
                'first_name' => 'Luc',
                'last_name' => 'Leveille',
                'account_status' => 1,
                'email' => 'leveillel@gmail.com',
                'email_verified_at' => '2020-09-08 11:23:54',
                'password' => '5f4dcc3b5aa765d61d8327deb882cf99',
                'remember_token' => NULL,
                'created_at' => '2020-09-08 11:23:54',
                'updated_at' => '2021-02-18 09:04:21',
                'deleted_at' => NULL,
                'public_email' => 1,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'Leveille Trim',
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => 0,
                'previous_login_date' => NULL,
                'last_login_date' => NULL,
                'login_count' => 0,
                'reasonToRegister' => '',
                'redirectAfterLogin' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'username' => 'haynesj',
                'first_name' => 'Jeffrey',
                'last_name' => 'Haynes',
                'account_status' => 1,
                'email' => 'haynesj@email.com',
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => NULL,
                'created_at' => '2020-10-10 04:20:43',
                'updated_at' => '2020-10-17 08:35:35',
                'deleted_at' => NULL,
                'public_email' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => NULL,
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => 1,
                'previous_login_date' => NULL,
                'last_login_date' => NULL,
                'login_count' => 0,
                'reasonToRegister' => '',
                'redirectAfterLogin' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'username' => 'haynesb',
                'first_name' => 'Brenda',
                'last_name' => 'Haynes',
                'account_status' => 1,
                'email' => 'brendahaynes@example.com',
                'email_verified_at' => '2020-09-08 11:24:40',
                'password' => '$2y$10$2wFWYndWpsbc8VsYQNR9ou6Hlw.Ctk8shv8/WtYfqwk1xcVspjfqu',
                'remember_token' => NULL,
                'created_at' => '2020-09-08 11:24:40',
                'updated_at' => '2021-05-28 11:52:59',
                'deleted_at' => NULL,
                'public_email' => 0,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => NULL,
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => 1,
                'previous_login_date' => '2020-10-26 12:00:11',
                'last_login_date' => '2020-10-27 09:12:00',
                'login_count' => 10,
                'reasonToRegister' => '',
                'redirectAfterLogin' => NULL,
            ),
            7 => 
            array (
                'id' => 20,
                'username' => 'author',
                'first_name' => 'Author',
                'last_name' => 'User',
                'account_status' => 0,
                'email' => 'stleroux@hotmail.ca2',
                'email_verified_at' => NULL,
                'password' => '$2y$10$4wRLKlJmly1k/hezj8ljOufFhv4wicjYlAYSCHo..tldO3tOUV85K',
                'remember_token' => NULL,
                'created_at' => '2020-06-05 11:54:16',
                'updated_at' => '2021-02-18 08:52:56',
                'deleted_at' => NULL,
                'public_email' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => NULL,
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 0,
                'invoicer_client' => 1,
                'previous_login_date' => '2020-10-04 19:07:41',
                'last_login_date' => '2020-10-10 00:12:49',
                'login_count' => 7,
                'reasonToRegister' => '',
                'redirectAfterLogin' => NULL,
            ),
            8 => 
            array (
                'id' => 25,
                'username' => 'khaynes',
                'first_name' => 'Kyle',
                'last_name' => 'Duperron-Haynes',
                'account_status' => 1,
                'email' => 'kdupe071@uottawa.ca',
                'email_verified_at' => NULL,
                'password' => '$2y$10$VSfDNbTDEY16FF2uKdd/NenWf7YJ3LfNGAMYXT7eF5omc0Z0lTQQK',
                'remember_token' => NULL,
                'created_at' => '2020-03-25 18:11:55',
                'updated_at' => '2020-09-03 00:46:42',
                'deleted_at' => NULL,
                'public_email' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'Kyle Duperron-Haynes',
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 16,
                'invoicer_client' => 1,
                'previous_login_date' => '2020-07-28 20:43:32',
                'last_login_date' => '2020-09-03 00:46:42',
                'login_count' => 9,
                'reasonToRegister' => '',
                'redirectAfterLogin' => NULL,
            ),
            9 => 
            array (
                'id' => 27,
                'username' => 'Tdot',
                'first_name' => 'Victoria',
                'last_name' => 'Duperron-Haynes',
                'account_status' => 1,
                'email' => 'vdg0909@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$JpgXRbmon6YQE8jZKEUVEecsEQAiFSvJBtG1DCL3h5cc9vIyYPscO',
                'remember_token' => NULL,
                'created_at' => '2020-03-30 17:35:38',
                'updated_at' => '2020-03-30 17:37:52',
                'deleted_at' => NULL,
                'public_email' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => NULL,
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => 1,
                'previous_login_date' => NULL,
                'last_login_date' => '2020-03-30 17:36:34',
                'login_count' => 1,
                'reasonToRegister' => '',
                'redirectAfterLogin' => NULL,
            ),
            10 => 
            array (
                'id' => 38,
                'username' => '',
                'first_name' => 'Jeffrey',
                'last_name' => 'Haynes',
                'account_status' => 1,
                'email' => 'haynes@email.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$YdhVER4.RXq.3/o8SJlpfufwu1oVQnoqlB/oBejz1PygTszWEQ0B.',
                'remember_token' => NULL,
                'created_at' => '2021-06-26 18:43:14',
                'updated_at' => '2021-06-26 18:43:14',
                'deleted_at' => NULL,
                'public_email' => NULL,
            'telephone' => '(123) 456-7890',
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'Haynes Underwear',
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 0,
                'invoicer_client' => 1,
                'previous_login_date' => NULL,
                'last_login_date' => NULL,
                'login_count' => 0,
                'reasonToRegister' => '',
                'redirectAfterLogin' => NULL,
            ),
            11 => 
            array (
                'id' => 39,
                'username' => '',
                'first_name' => 'Hugues',
                'last_name' => 'Leroux',
                'account_status' => 1,
                'email' => 'hugues@email.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$bBe0du17zfqPwirsL.IqYOyxUpRaaLG/tabwdjIKVNURKeDfXHLhu',
                'remember_token' => NULL,
                'created_at' => '2021-06-26 23:55:56',
                'updated_at' => '2021-06-26 23:55:56',
                'deleted_at' => NULL,
                'public_email' => NULL,
            'telephone' => '(232) 456-7878',
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'WadeRedden',
                'image' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 0,
                'invoicer_client' => NULL,
                'previous_login_date' => NULL,
                'last_login_date' => NULL,
                'login_count' => 0,
                'reasonToRegister' => '',
                'redirectAfterLogin' => NULL,
            ),
        ));
        
        
    }
}